# Basic n8n deployment configuration for Render
services:
- type: web
  name: n8n
  runtime: docker
  plan: starter
  envVars:
  - key: GENERIC_TIMEZONE
    value: Asia/Bangkok
  - key: NODE_ENV
    value: production
  - key: N8N_USER_FOLDER
    value: /opt/render/.n8n
  - key: N8N_PROTOCOL
    value: https
  - key: N8N_PORT
    value: "5678"
  - key: N8N_HOST
    value: n8n-0yly.onrender.com
  - key: N8N_EDITOR_BASE_URL
    value: https://n8n-0yly.onrender.com
  - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
    value: "false"
  - key: NODE_OPTIONS
    value: "--max-old-space-size=350"
  - key: N8N_LOG_LEVEL
    value: "error"
  - key: N8N_DISABLE_PRODUCTION_MAIN_PROCESS
    value: "true"
  - key: N8N_SKIP_WEBHOOK_DEREGISTRATION_SHUTDOWN
    value: "true"
  - key: N8N_DISABLE_UI
    value: "false"
  - key: N8N_METRICS
    value: "false"
  - key: N8N_RUNNERS_ENABLED
    value: "true"
  region: singapore
  disk:
    name: disk
    mountPath: /opt/render/.n8n
    sizeGB: 1
  autoDeployTrigger: commit
version: "1"