# Basic n8n deployment configuration for Render
services:
- type: web
  name: n8n
  runtime: image
  image:
    url: docker.n8n.io/n8nio/n8n:latest
  plan: starter
  envVars:
  - key: GENERIC_TIMEZONE
    value: Asia/Bangkok
  - key: NODE_ENV
    value: production
  - key: N8N_USER_FOLDER
    value: /home/node/.n8n
  - key: N8N_PROTOCOL
    value: https
  - key: N8N_PORT
    value: "5678"
  - key: N8N_HOST
    sync: false
  - key: N8N_EDITOR_BASE_URL
    sync: false
  region: singapore
  disk:
    name: disk
    mountPath: /home/node/.n8n
    sizeGB: 1
  autoDeployTrigger: commit
version: "1"